name = "CoilFunctions"
uuid = "0e2e25a7-1af4-42fd-b46d-35f8c1fa190d"
authors = ["[\"Daniel Berge", "\"Nexen Group", "Inc.\"]"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataStructures = "~0.17"
MappedArrays = "~0.2"
Roots = "~0.8"
ThreadTools = "~0.1"
Transducers = "~0.4"
Unitful = "~0.18"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
